export const GET_PRODUCTS = 'GET_PRODUCTS';

export const GET_CATEGORIES = 'GET_CATEGORIES';

export const GET_MINICART_PRODUCTS = 'GET_MINICART_PRODUCTS';
export const ADD_MINICART_PRODUCT = 'ADD_MINICART_PRODUCT';
export const DELETE_MINICART_PRODUCT = 'DELETE_MINICART_PRODUCT';
