export const GET_PRODUCTS = 'GET_PRODUCTS';
export const CLEAR_PRODUCTS_FROM_STORE = 'CLEAR_PRODUCTS_FROM_STORE';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CLEAR_CATEGORIES_FROM_STORE = 'CLEAR_CATEGORIES_FROM_STORE';

export const GET_MINICART_PRODUCTS = 'GET_MINICART_PRODUCTS';
export const ADD_MINICART_PRODUCT = 'ADD_MINICART_PRODUCT';
export const REFRESH_MINICART_PRODUCTS = 'REFRESH_MINICART_PRODUCTS';
export const DELETE_MINICART_PRODUCT = 'DELETE_MINICART_PRODUCT';
export const CLEAR_MINICART_PRODUCTS_FROM_STORE =
  'CLEAR_MINICART_PRODUCTS_FROM_STORE';

export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION';
